services:
  chat-app-backend:
    build:
      context: .
      dockerfile: ./dockerfile/main.dockerfile
    container_name: chat-app-backend
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - chat-app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=chat-app"

      - "traefik.http.routers.chat-api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.chat-api.entrypoints=web"
      - "traefik.http.routers.chat-api.service=chat-api-service"
      - "traefik.http.services.chat-api-service.loadbalancer.server.port=3000"

  emqx:
    image: emqx:latest
    container_name: emqx
    restart: unless-stopped
    networks:
      - chat-app
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
    expose:
      - "18083"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=chat-app"

      - "traefik.http.routers.emqx-dashboard.rule=Host(`emqx.localhost`)"
      - "traefik.http.routers.emqx-dashboard.entrypoints=web"
      - "traefik.http.routers.emqx-dashboard.service=emqx-dashboard-service"
      - "traefik.http.services.emqx-dashboard-service.loadbalancer.server.port=18083"

  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=chat-app"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - chat-app

networks:
  chat-app:
    external: true
    name: chat-app