global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "mysql"
    static_configs:
      - targets:
          - "mysql-exporter:9104"
  - job_name: "chat-app-backend"
    static_configs:
      - targets:
          - "chat-app-backend:3000"
  - job_name: "chat-app-frontend"
    static_configs:
      - targets:
          - "chat-app-frontend:5173"