global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "mysql"
    static_configs:
      - targets:
          - "mysql-exporter:9104"

  - job_name: "chat-app-backend"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "chat-app-backend:3000"

  - job_name: "chat-app-frontend-nginx"
    static_configs:
      - targets:
          - "chat-app-frontend-nginx-exporter:9113"